language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-20.0.0

    # The SDK version used to compile your project
    - android-20

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17
before_deploy: 
  - "chmod +x CI_Deployment_Script.sh"
  - "./CI_Deployment_Script.sh"
install:
  - "./gradlew android:assembleDebug"
  - "./gradlew desktop:dist"
before_script: "chmod +x NoTesting.sh"
script: ./NoTesting.sh
deploy:
  - provider: gcs
    skip-cleanup: true
    access_key_id: GOOGN5LIWR6GNM6NPPWV
    secret_access_key:
      secure: wVHIo5eBtdJVCr8IzF3Tj0M8uAGs0VWOqghOCnyhb3bX6fl3X+WzRPYIMqFVmG142EYiaNcnIVDkayNzoB3BCi5W9aVJcPWjJ3QL34DfY971FFVzt2q+8sT3KP4gsLD1+D081JEv1tSRkESiNwb2oStWL6bxoBvSNulhGsNQ3FDnPF46YdSwmOAHwu6wThEBbZAIYu8iZi31+slh1MK3PDewNaiuMvTqeV8wZq3pwH63d7HotdmAdYDnrRp8PABlZVU3vFea+mD8HiTS7qPHApwnESw1vTG0byklGpIy2CRvjiUFS40tTkYmVy/+wHqfEfvp63svELOex4qAQRMivgfgfJNoIBwbUZDy8VHWkgtQE00whoBb0wqAJ2wTExo2UricA2tPS/6qA5v9E5R7nkP3zRUFeulaFx/hZlwWGBSDf425pAgh5JyRjCGNhzWf1DGFKGiUhdePWRV1VlYcX9TXTRNinqR1H1LhBbVIgdSmzCJ1r+UuHaCmPRMVes1VFAcmIKlzkvC7CrNlgYVXK2SBkWkN5/KuOC/CLsneBuBJ99iRW1u3Lk0jHUJRECq3zdEU6jGVh3DllT3yRqNHOADP8Wqg6TimFJ8Q9lyQw9Fx1MmvNBNgv5n049QU15edd2obuy7dVomRipYzatLfCDcBxBRwFnV3fWxHA64S/Pg=
    bucket: kumquat_build_storage
    local_dir: upload
    on:
      all_branches: true
    
    
